### ISSUE TITLE
How to use custom branch/commit for test command

### ISSUE THREAD

**Issue by tfiedlerdejanze** [dependabot/cli#183]
:wave: we're using dependabot in a big Elixir umbrella project and are running into some issues lately. I've setup dependabot/cli with the following yaml config:

```
job:
  package-manager: mix
  allowed-updates:
    - update-type: all
  source:
    provider: github
    repo: private/repo
    directory: /
    commit: xxxx
    branch: xxxx
credentials:
  - type: hex-organization
    organization: boulevard
    key: $HEX_API_KEY
  - type: hex-repository
    repo: oban
    url: https://getoban.pro/repo
    auth-key: $OBAN_API_KEY
    public-key-fingerprint: $OBAN_FINGERPRINT
 ```
 
 When running this via:

```
dependabot test -f dependabot-test.yaml
```

It keeps downloading the mix files from the latest ref our `main` branch instead of using the `branch` + `commit` i've specified in the yaml `source:`. I am not sure if i am holding things wrong, or if that is a bug in dependabot/cli. Unfortunately i dont have a public repo at hand to reproduce this, but it should be fairly straight forward to test 🤞

**Comment by jakecoffman** [comment]
If you look at our smoke test run (I think you can see this?): https://github.com/dependabot/smoke-tests/actions/runs/6575795639/job/17863778814

It's fetching the file with the ref we specified in the [test file](https://github.com/dependabot/smoke-tests/blob/main/tests/smoke-hex.yaml):

> proxy | 2023/10/19 14:06:19 [002] GET [https://api.github.com:443/repos/dependabot/smoke-tests/contents/mix.exs?ref=832e37c1a7a4ef89feb9dc7cfa06f62205191994](https://api.github.com/repos/dependabot/smoke-tests/contents/mix.exs?ref=832e37c1a7a4ef89feb9dc7cfa06f62205191994) 

So it should be working!

I see `package-manager: mix` which doesn't work for me. Also try not specifying the `branch`, only specifying the `commit`. Not sure if that's the problem or not, but worth a shot!

**Comment by tfiedlerdejanze** [comment]
i am pretty sure it just worked 😅 looking at https://github.com/dependabot/cli/blob/main/internal/infra/run.go#L247 it should be `hex` instead of `mix` right?

With the following yaml

```
job:
  package-manager: hex
  allowed-updates:
    - update-type: all
  source:
    provider: github
    repo: private/repo
    directory: /
    commit: xxxx
credentials:
  - type: hex-organization
    organization: boulevard
    key: $HEX_API_KEY
  - type: hex-repository
    repo: oban
    url: https://getoban.pro/repo
    auth-key: $OBAN_API_KEY
    public-key-fingerprint: $OBAN_FINGERPRINT

```

this now fails with:

```
dependabot test -f dependabot-test.yaml
cli | 2023/10/19 15:17:58 Inserting $LOCAL_GITHUB_ACCESS_TOKEN into credentials
cli | 2023/10/19 15:17:58 Adding missing credentials-metadata into job definition
cli | 2023/10/19 15:17:58 unknown package manager:
```

kind of stomped on how i got it to work earlier though :D

**Comment by tfiedlerdejanze** [comment]
all I had to do was to group everything under `input:` in the yaml file:

```
input:
  job:
    package-manager: hex
    allowed-updates:
      - update-type: all
    source:
      provider: github
      repo: private/repo
      directory: /
      commit: xxxx
  credentials:
    # ...
```
