### ISSUE TITLE
job.yaml and gradle support

### ISSUE THREAD

**Issue by sblatnick** [dependabot/cli#261]
We are using this as a job.yaml to pass to dependabot/cli:
```
job:
    package-manager: gradle
    allowed-updates:
      - update-type: all
    source:
        provider: github
        repo: local/scan
        directory: /
credentials:
  - type: maven_repository
    url: nexus.redacted.com/maven-central
    username: redacted
    password: redacted
```
We see this error about missing the pom.xml:
```
ERROR Error during file fetching; aborting: /pom.xml not found
```
Am I doing something wrong with the config?  Can I get it to look for the build.gradle instead?
