### ISSUE TITLE
Error resolving private repository for Go using git

### ISSUE THREAD

**Issue by sblatnick** [dependabot/cli#281]
We have a Go repo we are attempting to scan with dependabot/cli, but it fails with:
```
 updater | 2024/02/15 21:44:00 INFO Handled error whilst updating golang.org/x/sys: dependency_file_not_resolvable {:message=>"go: bitbucket.redacted.com/scm/iums/user-session-service-go-proto-client.git@v1.15.0: reading bitbucket.redacted.com/scm/iums/user-session-service-go-proto-client.git/go.mod at revision v1.15.0: git ls-remote -q origin in /home/dependabot/go/pkg/mod/cache/vcs/6cf72754ff80bde10b25a250e064293bf43b37f4cbb34cede67f8ca5083e5255: exit status 128:\n\tfatal: unable to look up bitbucket.redacted.com (port 9418) (Temporary failure in name resolution)"}
```
Since this only seems to be happening on dependencies referencing a private repository, I've attempted to fix this with configuring auth in my job.yaml:
```
job:
    package-manager: go_modules
    allowed-updates:
      - update-type: all
    source:
        provider: github
        repo: local/scan
        directory: /
credentials:
  - type: git
    url: https://bitbucket.redacted.com/scm/
    username: redacted
    password: redacted
```
But the error remains unchanged and doesn't mention authenticating.

For go using a git dependency, does my job.yaml look right?
How can I resolve this dns look up?

The host should be reachable, as the repo this project is cloned from is hosted on the same bitbucket as the module we import.  Also, we have other private registries for other languages which dependabot/cli has accessed.
