### ISSUE TITLE
Private registry url is incorrect

### ISSUE THREAD

**Issue by danpowell88** [dependabot/cli#355]
Trying to use the cli to debug an issue with hanging (which could be related to this issue I guess).

Config:
```
job:
    package-manager: npm_and_yarn
    allowed-updates:
      - update-type: all
    source:
        provider: github
        repo: org/repo
        directory: /src/ui
credentials:
  - type: npm-registry
    url: https://nuget.org.com/npm/npm-org
    token: xxxxxxx
  - type: npm-registry
    url: https://nuget.org.com/npm/npm-anotherorg
    token: xxxxxxx
```  

My .npmrc file looks like the following an lives in the /src/ui/.npmrc location

```
registry=https://registry.npmjs.org
@pkg3:registry=https://nuget.org.com/npm/npm-anotherorg/
@org:registry=https://nuget.org.com/npm/npm-org/
@pkg2:registry=https://nuget.org.com/npm/npm-org/
scripts-prepend-node-path=true
```

When dependabot runs it outputs the following line
```
    "data": {
        "dependencies": [
            {
                "name": "@pkg3/sd-angular",
                "requirements": [
                    {
                        "file": "package.json",
                        "groups": [
                            "dependencies"
                        ],
                        "requirement": "^15.0.3",
                        "source": {
                            "type": "registry",
                            "url": "https://nuget.org.com"
                        }
                    }
                ],
                "version": "15.0.3"
            },
....
```

And then later

`{"data":{"error-type":"private_source_authentication_failure","error-details":{"source":"nuget.org.com"}},"type":"record_update_job_error"}`

I suspect its not expecting there to be subdirectories in the path or something else odd is going on?
