### ISSUE TITLE
Trying to test uv

### ISSUE THREAD

**Issue by adiberk** [dependabot/cli#415]
Trying to test uv on my local
```
version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "uv"
    directory: "/"
    labels:
      - "dependencies"
    schedule:
      interval: "weekly"
```

When I run the command
`dependabot test -f .github/dependabot.yml`

I get the following error
    cli | 2025/03/25 14:45:46 unknown package manager:
