### ISSUE TITLE
Error with python-index token with azure

### ISSUE THREAD

**Issue by fensoft** [dependabot/cli#445]
Hi,

I've put this as a `dependabot.yml`:

```
version: 2

registries:
  bcp:
    type: python-index
    url: https://pkgs.dev.azure.com/.../pypi/simple/
    token: <token>

updates:
- package-ecosystem: pip
  directory: "/"
  registries:
    - bcp
```

While doing this:
`dependabot update --local . --provider azure pip <repo>`

I got a 403 error on fetching `https://pkgs.dev.azure.com/.../pypi/simple/<package>/`

But I got the content while doing this:
`curl https://pkgs.dev.azure.com/.../pypi/simple/<package>/ -H 'Authorization: Bearer <token>' -X GET`

What have I done wrong ?
